### ISSUE TITLE
Strange issue with raptor on Parrot OS 

### ISSUE THREAD

**Issue by RichardRMatthews** [CoolerVoid/raptor_waf#11]
Raptor WAF seems like a really cool and usefule tool , but sadly I could not test it in action . On my raspberries it does not work at all ( I might open a seperate issue for that ) , but on my Parrot-OS laptop I get some errors too . I used the default settings provided in the doc : 

![raptorwaf_issue01](https://user-images.githubusercontent.com/29675503/40193958-2b134534-5a09-11e8-8d0e-07fd3c84dd43.png)

I could not connect , so I looked if it was listening and it was :

![raptorwaf_issue02](https://user-images.githubusercontent.com/29675503/40193965-336420aa-5a09-11e8-9498-8c2a520ac25d.png)

Then I made a firewall rule for both port 80 and 8883 : 

![raptorwaf_issue03](https://user-images.githubusercontent.com/29675503/40193972-39a42e24-5a09-11e8-906f-0dfe72fb24ae.png)

But when I tried to connect via firefox it timed out : 

![raptorwaf_issue04](https://user-images.githubusercontent.com/29675503/40193987-3dc14e4c-5a09-11e8-89cc-4a035137ecb3.png)

And raptor crashed with the following error : 

![raptorwaf_issue05](https://user-images.githubusercontent.com/29675503/40193989-40e03070-5a09-11e8-981c-7e12a0951f1f.png)

Another time it said "sending http request " , but was stuck in an endless loop without timeout .

Really hope you can help me . I would like to try raptor WAF in action .

Thank you .

**Comment by CoolerVoid** [comment]
Please fix the screenshots...i cannot see the images.

**Comment by RichardRMatthews** [comment]
Does it work now ?

**Comment by CoolerVoid** [comment]
Try to open on  browser the full path http://IP_MACHINE:8883/index.html
look that video https://www.youtube.com/watch?v=VtL0apDv1N4

**Comment by RichardRMatthews** [comment]
Thank you , I will provide more screenshots tomorrow concering the crash .
