### ISSUE TITLE
Unexpected crashes when testing for vulnerabilities .

### ISSUE THREAD

**Issue by RichardRMatthews** [CoolerVoid/raptor_waf#12]
First I started raptor and bound it to port 20001 , which worked . 

![crash01](https://user-images.githubusercontent.com/29675503/40238375-4a758b1c-5ab3-11e8-83ac-2c6e2c696f80.png)

![crash02](https://user-images.githubusercontent.com/29675503/40238392-52e80d4c-5ab3-11e8-8689-75eb97ff1994.png)

But when I tried to attack test.php on port 20001 with sqlmap , raptor crashed and Sqlmap refused the connection . 

![crash03](https://user-images.githubusercontent.com/29675503/40238458-88b30472-5ab3-11e8-944c-d88b134ed1ad.png)
![crash05](https://user-images.githubusercontent.com/29675503/40238486-9a34a872-5ab3-11e8-9d8c-f1d2162b1ef1.png)

I could not bind raptor to the same port after the crash . 

![crash06](https://user-images.githubusercontent.com/29675503/40238520-b1f95732-5ab3-11e8-87e1-def15369c96e.png)

For some reason I could not reproduce yesterdays error with wafw00f , but I used the wapiti web-vuln scanner instead . 

![crash07](https://user-images.githubusercontent.com/29675503/40238707-47474934-5ab4-11e8-922f-f92cd9377b94.png)

And again It crashed with segmentation fault . 

![crash08](https://user-images.githubusercontent.com/29675503/40238733-593ddc0c-5ab4-11e8-9eda-1acc9da69ab2.png)

But afterwards I could immeditatly bind raptor to the same port unlike with sqlmap .

**Comment by CoolerVoid** [comment]
Ok thank you for feedback...
Next work is fix  that  crashes.

cheers

**Comment by RichardRMatthews** [comment]
Ok , thanks .

**Comment by CoolerVoid** [comment]
Today i make a simple update... now try to run that following  command:

$ bin/Raptor -h 127.0.0.1 -p 80 -r 8883 -w 0 -o resultwaf -m pcre

So set rules in config/regex_rules.txt
In rules  file you can use perl regex based.
https://www.pcre.org/

To run in  DFA mode, edit makefile and remove stack protector...
I don't recommend that mode now, because continues in development, is not mature enough.

**Comment by RichardRMatthews** [comment]
Thank you , I will try it today.
