### ISSUE TITLE
Help!! Please.

### ISSUE THREAD

**Issue by lgcambero** [CoolerVoid/raptor_waf#4]
![sin titulo](https://cloud.githubusercontent.com/assets/11602705/18687658/83c7c13e-7f57-11e6-8a64-4478ed1fbb65.jpg)

Tks.

**Comment by CoolerVoid** [comment]
So, you need use "./bin/Raptor" not "cd bin/; ./Raptor".
real path is raptor_waf... use this root path...

Cheers

**Comment by lgcambero** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/11602705/18688147/7385af46-7f59-11e6-859d-a7c52d1687c8.jpg)

:(

**Comment by CoolerVoid** [comment]
Humn... this is not normal...
i test with mutillidae... and here runs...
SOOOOO You need use argv **--host**

example:
 bin/Raptor --host 127.0.0.1 -p 80 -r 9999 -w 2 --log test

more attention sir... 

thank you to report

**Comment by lgcambero** [comment]
Great!! It works.
Stay tuned for new features.
Regards!!

**Comment by pujiarahman** [comment]
hi, some thing wrong

gcc -W -Wall -O2 -fstack-protector-all  lib/BSD/strsec.c -D_FORTIFY_SOURCE=2 -c src/*.c
In file included from src/match_algorithms.c:2:0:
src/match_algorithms.h:6:18: fatal error: pcre.h: No such file or directory
compilation terminated.
In file included from src/matchlist.c:4:0:
src/match_algorithms.h:6:18: fatal error: pcre.h: No such file or directory
compilation terminated.
Makefile:17: recipe for target 'Raptor' failed
make: *** [Raptor] Error 1
root@xecho:/home/sa/raptor/raptor_waf#

thanks

**Comment by conviso-code** [comment]
So you need install lib pcre to compile and run
Follow this  step:

Debian based linux:
# apt-get  install libpcre3-dev

Rpm based  linux:
yum install pcre-devel

Or search per  name "pcre" in Ports if you use  MacOS  or BSD like etc

**Comment by CoolerVoid** [comment]
So you need install lib pcre to compile and run
Follow this  step:

Debian based linux:
```
 apt-get  install libpcre3-dev
```
Rpm based  linux:
```
yum install pcre-devel
```
Or search per  name "pcre" in Ports if you use  MacOS  or BSD like etc

**Comment by pujiarahman** [comment]
hi, thanks, 
now is worked

**Comment by irmalistia** [comment]
hello what does it means? after I typed cd raptor_waf; make;
the result is I got warning that is no longer supported

gcc: warning: switch ‘-mmitigate-rop’ is no longer supported
rm -f *.o Raptor

thankyou

**Comment by CoolerVoid** [comment]
Today i make a patch fix in "make" file...
Excuse me about that, please try compile again... 

If you want a project with strong performance in WAF look this following
https://github.com/CoolerVoid/OctopusWAF

Thank you

**Comment by irmalistia** [comment]
hello, I still curious about raptorwaf hehe
I tried one more time, and the result is like this when I started it
tcp_cannot_connect_to_stamp()cannot connect

![Capture1](https://user-images.githubusercontent.com/73868003/109678292-0ea22c80-7bad-11eb-94ca-89a8eac7b7b2.JPG)

**Comment by irmalistia** [comment]
Thank you for your response..

I tried OctopusWAF, the result is like this
Is this successful though?

![OWAF1](https://user-images.githubusercontent.com/73868003/109682177-c08f2800-7bb0-11eb-9f9f-e3ae58c89eb6.JPG)

and I tried raptorwaf also and it works!
![RAPTOR1](https://user-images.githubusercontent.com/73868003/109682498-0d72fe80-7bb1-11eb-9a55-9dec1b690444.JPG)

**Comment by CoolerVoid** [comment]
Ok, excuse me. issues about octopusWAF please write in octopusWAF issues list...

First problem, Kali don't use stable version of GCC (GNU C compiler), because uses current version, current version have a lot BUGs. Don't belive in current version, never...

To understand in practical uou could to start looking the video demos in README.md of project.

So if you have other questions, i am here to help.
thank you for feedback

cheers
