### ISSUE TITLE
it just can protect appliction which in same server?

### ISSUE THREAD

**Issue by calistochen** [CoolerVoid/raptor_waf#5]
it just can protect appliction which in same server?

**Comment by CoolerVoid** [comment]
Yes ! you can protect the same server, but need make some configurations.

One way to do this, you need add some rules at firewall, at OpenBSD firewall for example you can do something like this:
```
# OpenBSD + Raptor
# ifconfig to choice the ethernet macro
placa = "bge0"
nginxmachine = "127.0.0.1"

set optimization normal
set require-order yes
# block fingerprint attacks like "nmap -O ip_do_server"
set fingerprints "/etc/pf.os"
set skip on lo0

# normalize
scrub all reassemble tcp
scrub out all no-df max-mss 1492 random-id
antispoof for $placa inet

# block nmap scans 
block in quick proto tcp flags FUP/WEUAPRSF
block in quick proto tcp flags WEUAPRSF/WEUAPRSF
block in quick proto tcp flags SRAFU/WEUAPRSF
block in quick proto tcp flags /WEUAPRSF
block in quick proto tcp flags SR/SR
block in quick proto tcp flags SF/SF
block drop in quick on $placa from any os { NMAP }

# block all connections
block all
# pass NGINX port 8090 to 127.0.01 only
pass in log quick on $placa inet proto tcp from $nginxmachine  to any port 8090 flags S/SA
# free HTTP and BIND
pass in quick on $placa inet proto tcp to $placa port { http } flags S/SA keep state
pass in quick on $placa inet proto tcp to $placa port { domain } flags S/SA keep state 
```
So at this example of PF, you need put NGINX at port 8090, with this Raptor redirect 8090 to listening port  at number 80, But port 8090 is close to all other IPs, but Open to "127.0.0.1".

This example is a good path, but at the future you need free the port 443 to use TLS...

cheers

**Comment by calistochen** [comment]
i think maybe i can do something that let raptor to protect another application in the same subnet.Run under the layer 2?

**Comment by CoolerVoid** [comment]
Other way you can use iptables... have a lot alternatives.
Not have one better.
